package com.example.karrotmarket.domain;

public enum Category {
    DIGITAL_DEVICE,
    HOUSEHOLD_APPLIANCES,
    FURNITURE_INTERIOR,
    LIVING_KITCHEN,
    INFANT_CHILD,
    INFANT_BOOKS,
    WOMAN_CLOTHING,
    WOMAN_MISCELLANEOUS,
    MEN_FASHION_MISCELLANEOUS,
    BEAUTY,
    SPORTS_LEISURE,
    HOBBY_GAME_DISCOGRAPHY,
    BOOKS,
    TICKET_EXCHANGETICKET,
    PROCESSED_FOOD,
    PET_SUPPLIES
}
